### PR TITLE
第一周作業

### PR DESCRIPTION
**Pull request by Lswben93**
林仕偉第五次修正

針對"data" field in the response(格式)做出修正

http://44.198.152.78:3000/api/attractions?page=0&name=北
http://44.198.152.78:3000/api/attractions?page=0
http://44.198.152.78:3000/api/attraction/301

### CODE REVIEW

**Comment by cwpeng** [comment]
Better, but there are more than 1 image URLs for each attraction actually. And your response data contains only 1 image URL for each attraction. Fix it and leave comment for me to review again. You don't need to close and open new pull request every time.

**Comment by Lswben93** [comment]
林仕偉第六次修正
針對圖片顯示做出修正

http://44.198.152.78:3000/api/attractions?page=0&name=北
http://44.198.152.78:3000/api/attractions?page=0
http://44.198.152.78:3000/api/attraction/600

**Comment by cwpeng** [comment]
Format of http://44.198.152.78:3000/api/attraction/600 is incorrect. Use jsonify() to format JSON data will be much better than connecting strings yourself.

**Comment by Lswben93** [comment]
林仕偉第六次修正
老師我可以先用strings表示嗎?
我身體還沒回復到之前的狀態，
還在吃藥調整中，
所以目前沒辦法使用電腦太久。


http://44.198.152.78:3000/api/attractions?page=0&name=北
http://44.198.152.78:3000/api/attractions?page=0
http://44.198.152.78:3000/api/attraction/600

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
